import { Book } from "./types";

export const BOOK_CATEGORIES = [
  "Psychology",
  "Technology",
  "Design",
  "History",
  "Science",
];

export const BOOKS: Book[] = [
  {
    id: 1,
    macroCategory: "Educational",
    category: "Technology",
    title: "The Attention Merchants",
    author: "Tim Wu",
    coverEmoji: "📕",
    trending: true,
    pages: 416,
    blurb:
      "A history of how industries learned to capture and resell human attention, from early advertising to the modern feed.",
    tags: ["attention", "media"],
  },
  {
    id: 2,
    macroCategory: "Educational",
    category: "Psychology",
    title: "Four Thousand Weeks",
    author: "Oliver Burkeman",
    coverEmoji: "📗",
    trending: true,
    pages: 288,
    blurb:
      "A short book on time management that argues most productivity advice misses the actual problem: there isn't enough time, and that's fine.",
    tags: ["time", "productivity"],
  },
  {
    id: 3,
    macroCategory: "Educational",
    category: "Technology",
    title: "Digital Minimalism",
    author: "Cal Newport",
    coverEmoji: "📘",
    trending: true,
    pages: 304,
    blurb:
      "A practical philosophy for using technology intentionally rather than compulsively, with a 30-day reset plan.",
    tags: ["attention", "technology"],
  },
  {
    id: 4,
    macroCategory: "Educational",
    category: "Psychology",
    title: "The Shallows",
    author: "Nicholas Carr",
    coverEmoji: "📙",
    trending: false,
    pages: 280,
    blurb:
      "An argument that the internet is reshaping how we read and think, often trading depth of focus for breadth of access.",
    tags: ["attention", "cognition"],
  },
  {
    id: 5,
    macroCategory: "Educational",
    category: "Psychology",
    title: "Stolen Focus",
    author: "Johann Hari",
    coverEmoji: "📓",
    trending: true,
    pages: 368,
    blurb:
      "An investigation into why attention spans are shrinking, drawing on interviews with scientists across the world.",
    tags: ["attention", "cognition"],
  },
  {
    id: 6,
    macroCategory: "Educational",
    category: "Psychology",
    title: "Indistractable",
    author: "Nir Eyal",
    coverEmoji: "📔",
    trending: false,
    pages: 256,
    blurb:
      "A framework for controlling your own attention, written by someone who previously taught companies how to capture it.",
    tags: ["attention", "habits"],
  },
  {
    id: 7,
    macroCategory: "Educational",
    category: "Psychology",
    title: "Deep Work",
    author: "Cal Newport",
    coverEmoji: "📒",
    trending: false,
    pages: 296,
    blurb:
      "A case for focused, undistracted work as a skill that's becoming rarer and more valuable at the same time.",
    tags: ["focus", "productivity"],
  },
  {
    id: 8,
    macroCategory: "Educational",
    category: "History",
    title: "Amusing Ourselves to Death",
    author: "Neil Postman",
    coverEmoji: "📚",
    trending: false,
    pages: 208,
    blurb:
      "A classic argument that entertainment-driven media changes the substance of public discourse, not just its style.",
    tags: ["media", "history"],
  },
  {
    id: 9,
    macroCategory: "Educational",
    category: "Design",
    title: "The Design of Everyday Things",
    author: "Don Norman",
    coverEmoji: "📖",
    trending: false,
    pages: 368,
    blurb:
      "A foundational look at why some objects are intuitive to use and others are not, and what that says about design itself.",
    tags: ["design"],
  },
  {
    id: 10,
    macroCategory: "Educational",
    category: "Science",
    title: "A Short History of Nearly Everything",
    author: "Bill Bryson",
    coverEmoji: "📔",
    trending: true,
    pages: 544,
    blurb:
      "A wide tour through science, from the size of an atom to the size of the universe, written for total beginners.",
    tags: ["science"],
  },
  {
    id: 11,
    macroCategory: "Entertainment",
    category: "History",
    title: "Flagged demo: restricted content placeholder",
    author: "Demo account",
    coverEmoji: "⚠️",
    trending: false,
    pages: 1,
    blurb:
      "This entry exists only to demonstrate the content moderation system for books. It is filtered out entirely in kid mode, and permanently blurred in adult mode.",
    flagged: true,
    tags: ["flagged-demo"],
  },
];
