import { ContentItem, MacroCategory } from "./types";

export const MACRO_CATEGORIES: MacroCategory[] = [
  "Educational",
  "Entertainment",
  "Wellbeing",
  "Arts & Culture",
];

export const MICRO_CATEGORIES_BY_MACRO: Record<MacroCategory, string[]> = {
  Educational: ["Science", "History", "Design", "Maths", "Languages"],
  Entertainment: ["Music", "News", "Cooking"],
  Wellbeing: ["Mindfulness", "Nature", "Sleep"],
  "Arts & Culture": ["Visual Art", "Film & Animation", "Theatre"],
};

export const CATEGORIES = Object.values(MICRO_CATEGORIES_BY_MACRO).flat();

export const CONTENT: ContentItem[] = [
  {
    id: 1,
    type: "deep",
    macroCategory: "Educational",
    category: "Science",
    title: "How fusion reactors actually contain plasma",
    creator: "Helion Notes",
    duration: "9:42",
    emoji: "⚛️",
    body: "Magnetic confinement isn't one trick — it's a layered system of coils, pressure balance, and feedback loops that fight instability thousands of times a second. Here's the physics in plain terms, with the failure modes engineers actually worry about.",
    tags: ["physics", "energy", "engineering"],
  },
  {
    id: 2,
    type: "short",
    macroCategory: "Educational",
    category: "Science",
    title: "Mind-blowing space fact??",
    creator: "@cosmicfacts99",
    duration: "0:12",
    emoji: "🚀",
    body: "Saturn's rings are basically paper thin compared to how wide they are!! Like and follow for more.",
    tags: ["space"],
  },
  {
    id: 3,
    type: "deep",
    macroCategory: "Educational",
    category: "Science",
    title: "Why CRISPR edits sometimes miss their target",
    creator: "Bench & Bio",
    duration: "7:15",
    emoji: "🧬",
    body: "Off-target edits aren't random noise — they follow patterns tied to chromatin structure and guide RNA design. A walkthrough of what's actually happening at the molecular level, and how labs are correcting for it.",
    tags: ["biology", "genetics"],
  },
  {
    id: 4,
    type: "short",
    macroCategory: "Educational",
    category: "Science",
    title: "POV: you forgot the control group",
    creator: "@labmemes",
    duration: "0:08",
    emoji: "🔬",
    body: "Science be like that sometimes.",
    tags: ["biology"],
  },
  {
    id: 5,
    type: "deep",
    macroCategory: "Entertainment",
    category: "Music",
    title: "The modal scale that built 70s jazz fusion",
    creator: "Theory & Tone",
    duration: "11:03",
    emoji: "🎷",
    body: "Dorian mode shows up everywhere in this era, but not by accident — it solves a specific harmonic problem that major scales can't. A close listen to how Hancock and Shorter used it deliberately.",
    tags: ["music theory"],
  },
  {
    id: 6,
    type: "short",
    macroCategory: "Entertainment",
    category: "Music",
    title: "This beat goes SO hard",
    creator: "@beatsdaily",
    duration: "0:10",
    emoji: "🎵",
    body: "Wait for the drop.",
    tags: ["music"],
  },
  {
    id: 7,
    type: "short",
    macroCategory: "Entertainment",
    category: "Music",
    title: "Rating songs by vibe only",
    creator: "@vibecheckmusic",
    duration: "0:14",
    emoji: "🎧",
    body: "This one's a 10/10, no skip.",
    tags: ["music"],
  },
  {
    id: 8,
    type: "deep",
    macroCategory: "Entertainment",
    category: "News",
    title: "What the new shipping tariffs actually change",
    creator: "The Long Read",
    duration: "8:30",
    emoji: "🌍",
    body: "Past the headlines: which industries absorb the cost, which pass it to consumers, and the three-year timeline economists are actually watching. Context most coverage skips.",
    tags: ["economics", "world"],
  },
  {
    id: 9,
    type: "short",
    macroCategory: "Entertainment",
    category: "News",
    title: "You won't believe what happened today",
    creator: "@newsflash24",
    duration: "0:09",
    emoji: "📰",
    body: "This changes everything (it doesn't).",
    tags: ["news"],
  },
  {
    id: 10,
    type: "deep",
    macroCategory: "Entertainment",
    category: "Cooking",
    title: "The Maillard reaction, and why your sear is pale",
    creator: "Kitchen Chemistry",
    duration: "6:18",
    emoji: "🍳",
    body: "It's not heat alone — it's heat plus surface moisture plus protein structure. Once you understand the actual chemistry, you'll never wonder why restaurant steaks look different from home ones.",
    tags: ["cooking", "chemistry"],
  },
  {
    id: 11,
    type: "short",
    macroCategory: "Entertainment",
    category: "Cooking",
    title: "3 ingredient pasta hack",
    creator: "@quickeats",
    duration: "0:11",
    emoji: "🍝",
    body: "Trust me on this one.",
    tags: ["cooking"],
  },
  {
    id: 12,
    type: "short",
    macroCategory: "Entertainment",
    category: "Cooking",
    title: "This kitchen gadget changed my life",
    creator: "@gadgetgirl",
    duration: "0:13",
    emoji: "🥄",
    body: "Link in bio.",
    tags: ["cooking"],
  },
  {
    id: 13,
    type: "deep",
    macroCategory: "Educational",
    category: "History",
    title: "The trade routes that moved before empires did",
    creator: "Long Memory",
    duration: "10:27",
    emoji: "🏺",
    body: "Empires get the credit, but the merchant networks that connected them often predate the conquest by centuries. A look at how goods, language, and disease moved long before flags did.",
    tags: ["history", "trade"],
  },
  {
    id: 14,
    type: "short",
    macroCategory: "Educational",
    category: "History",
    title: "History teacher never told you this",
    creator: "@historyhacks",
    duration: "0:10",
    emoji: "📜",
    body: "They don't want you to know.",
    tags: ["history"],
  },
  {
    id: 15,
    type: "deep",
    macroCategory: "Educational",
    category: "Design",
    title: "Why grid systems feel calmer than feeds",
    creator: "Studio Notes",
    duration: "7:51",
    emoji: "📐",
    body: "Infinite scroll removes the brain's sense of progress — there's no edge, so there's no stopping point. Grids restore that edge. A breakdown of why bounded layouts reduce compulsive use.",
    tags: ["design", "attention"],
  },
  {
    id: 16,
    type: "short",
    macroCategory: "Educational",
    category: "Design",
    title: "Rating fonts in 10 seconds",
    creator: "@typetok",
    duration: "0:10",
    emoji: "🔤",
    body: "This one's actually so clean.",
    tags: ["design"],
  },
  {
    id: 17,
    type: "short",
    macroCategory: "Educational",
    category: "Design",
    title: "Redesigning your room in POV",
    creator: "@aesthetichome",
    duration: "0:15",
    emoji: "🛋️",
    body: "Wait for the reveal.",
    tags: ["design"],
  },
  {
    id: 18,
    type: "short",
    macroCategory: "Entertainment",
    category: "News",
    title: "Extreme prank gone wrong (clickbait demo)",
    creator: "@flagged_demo_account",
    duration: "0:16",
    emoji: "⚠️",
    body: "This item is included only to demonstrate the content moderation system. In kid mode it is filtered out entirely. In adult mode it is permanently blurred and cannot be unblurred.",
    flagged: true,
    tags: ["flagged-demo"],
  },
  {
    id: 19,
    type: "deep",
    macroCategory: "Educational",
    category: "Science",
    title: "Flagged demo: graphic content placeholder",
    creator: "@flagged_demo_account",
    duration: "4:00",
    emoji: "⚠️",
    body: "This item exists only to demonstrate moderation on long-form content too. It is never visible to a kid profile, and an adult profile only ever sees the blurred placeholder, never the content itself.",
    flagged: true,
    tags: ["flagged-demo"],
  },
  {
    id: 20,
    type: "deep",
    macroCategory: "Educational",
    category: "Maths",
    title: "Why prime numbers refuse to follow a pattern",
    creator: "Number Theory Notes",
    duration: "8:12",
    emoji: "🔢",
    body: "Mathematicians have searched for centuries for a formula that predicts primes, and the gaps between them still resist easy explanation. A look at what's actually been proven, and what's still open.",
    tags: ["maths", "number theory"],
  },
  {
    id: 21,
    type: "short",
    macroCategory: "Educational",
    category: "Maths",
    title: "This number trick always works",
    creator: "@quickmath",
    duration: "0:11",
    emoji: "🧮",
    body: "Try it on any number, seriously.",
    tags: ["maths"],
  },
  {
    id: 22,
    type: "deep",
    macroCategory: "Educational",
    category: "Languages",
    title: "Why English spelling makes no sense (and how it got that way)",
    creator: "Word Origins",
    duration: "9:05",
    emoji: "🔡",
    body: "English spelling looks broken because it's actually layered history — Old English, French invasion, Latin scholars, and a printing press that froze spellings before pronunciation finished shifting.",
    tags: ["language", "etymology"],
  },
  {
    id: 23,
    type: "short",
    macroCategory: "Educational",
    category: "Languages",
    title: "Say this phrase in 5 languages",
    creator: "@polyglotpractice",
    duration: "0:13",
    emoji: "🗣️",
    body: "Number 4 will surprise you.",
    tags: ["language"],
  },
  {
    id: 24,
    type: "deep",
    macroCategory: "Wellbeing",
    category: "Mindfulness",
    title: "What's actually happening in your brain during meditation",
    creator: "Calm Science",
    duration: "7:40",
    emoji: "🧘",
    body: "Brain scans of experienced meditators show measurable changes in attention networks and stress response. Here's what's backed by research, and what's still more belief than evidence.",
    tags: ["mindfulness", "neuroscience"],
  },
  {
    id: 25,
    type: "short",
    macroCategory: "Wellbeing",
    category: "Mindfulness",
    title: "Try this 10 second breathing trick",
    creator: "@calmtips",
    duration: "0:10",
    emoji: "😌",
    body: "Works anywhere, anytime.",
    tags: ["mindfulness"],
  },
  {
    id: 26,
    type: "deep",
    macroCategory: "Wellbeing",
    category: "Nature",
    title: "How forests communicate underground",
    creator: "Field Notes",
    duration: "8:55",
    emoji: "🌲",
    body: "Tree roots connect through fungal networks that can move nutrients and warning signals between plants. It's not quite the internet of trees the headlines suggest, but it's still remarkable.",
    tags: ["nature", "biology"],
  },
  {
    id: 27,
    type: "short",
    macroCategory: "Wellbeing",
    category: "Nature",
    title: "This is the rarest cloud formation",
    creator: "@skywatcher",
    duration: "0:09",
    emoji: "☁️",
    body: "Spotted this once in a decade.",
    tags: ["nature"],
  },
  {
    id: 28,
    type: "deep",
    macroCategory: "Wellbeing",
    category: "Sleep",
    title: "What your brain is actually doing while you sleep",
    creator: "Sleep Science Weekly",
    duration: "9:30",
    emoji: "🌙",
    body: "Sleep isn't downtime — it's when the brain clears metabolic waste, consolidates memory, and runs maintenance that simply can't happen while you're awake. A walkthrough of the different sleep stages.",
    tags: ["sleep", "neuroscience"],
  },
  {
    id: 29,
    type: "short",
    macroCategory: "Wellbeing",
    category: "Sleep",
    title: "Why you wake up at 3am every night",
    creator: "@sleeptips",
    duration: "0:12",
    emoji: "🛏️",
    body: "It's more common than you think.",
    tags: ["sleep"],
  },
  {
    id: 30,
    type: "deep",
    macroCategory: "Arts & Culture",
    category: "Visual Art",
    title: "How Renaissance painters faked depth on a flat wall",
    creator: "Art History Lab",
    duration: "8:20",
    emoji: "🎨",
    body: "Linear perspective wasn't always obvious — it had to be invented, tested, and refined. A look at the mathematics hiding inside some of the most famous paintings in history.",
    tags: ["art", "history"],
  },
  {
    id: 31,
    type: "short",
    macroCategory: "Arts & Culture",
    category: "Visual Art",
    title: "Spot the hidden detail in this painting",
    creator: "@arttrivia",
    duration: "0:14",
    emoji: "🖼️",
    body: "Most people miss this completely.",
    tags: ["art"],
  },
  {
    id: 32,
    type: "deep",
    macroCategory: "Arts & Culture",
    category: "Film & Animation",
    title: "The animation trick that makes movement feel alive",
    creator: "Frame by Frame",
    duration: "7:05",
    emoji: "🎬",
    body: "Squash and stretch isn't just a Disney rule of thumb — it mirrors how real objects deform under force, which is why animation that ignores it feels stiff even when it's technically smooth.",
    tags: ["animation", "design"],
  },
  {
    id: 33,
    type: "short",
    macroCategory: "Arts & Culture",
    category: "Film & Animation",
    title: "This animation took 3 years to make",
    creator: "@behindthescenes",
    duration: "0:15",
    emoji: "🎞️",
    body: "Frame by frame, by hand.",
    tags: ["animation"],
  },
  {
    id: 34,
    type: "deep",
    macroCategory: "Arts & Culture",
    category: "Theatre",
    title: "Why Greek theatre masks weren't just for hiding faces",
    creator: "Stagecraft History",
    duration: "6:50",
    emoji: "🎭",
    body: "Ancient masks amplified voice, projected emotion to the back row, and let one actor play multiple roles in a single performance — design solving real, practical problems.",
    tags: ["theatre", "history"],
  },
  {
    id: 35,
    type: "short",
    macroCategory: "Arts & Culture",
    category: "Theatre",
    title: "The loudest moment in theatre history",
    creator: "@stagefacts",
    duration: "0:11",
    emoji: "🎪",
    body: "Audiences reportedly screamed.",
    tags: ["theatre"],
  },
];
